### ISSUE TITLE
Mikrotik backup implementation

### ISSUE THREAD

**Issue by amgxv** [MajorcaDevs/mdbackup#11]
Mikrotik backups via ssh.

Access to the router (ssh)
- Passing password as clear text with **[sshpass](https://www.cyberciti.biz/faq/noninteractive-shell-script-ssh-password-provider/)** (not recommended)
- [Using ssh keys](https://jcutrer.com/howto/networking/mikrotik/routeros-ssh-publickeyauth-rsa-keys) (recommended)

Commands to be executed
- Run backup : `ssh admin@router /system backup save name="<backup_name>"`
- Get backup from router : `scp admin@router:"<backup_name>" <local_dir>` 

Other commands that can be useful
- Export scripts : `/system script export file=scripts`
- Export system configuration : `/system export file=system`
- Export global configuration as .rsc : `/export file=router`

It would be nice to : 
- Save the backup as something like : "$hostname-$date" (majorcadevs-12-03-2019)
- Delete past day backup and always keep the daily backup at the router

**Comment by melchor629** [comment]
**To implement**

A function in `utils.sh` which will receive the following parameters:

 - The IP or hostname of the router
 - An optional parameter `--export-scripts`
 - An optional parameter `--export-sys-conf`
 - An optional parameter `--export-global-conf`

By default, will make a backup from the MikroTik device, but with the previous optional parameters, someone can export the rest of things if desired.

The names of the files in the MikroTik device must contain the date (use `date "+%Y%m%d-%H%m"` on the function to generate a date-time string). But the files in the computer which runs `mdbackup` must store the files in a folder named `mikrotik-${IP}` and the names of the files without the date-time string.
