### ISSUE TITLE
User parameter on database docker action is interpreted as system user

### ISSUE THREAD

**Issue by amgxv** [MajorcaDevs/mdbackup#83]
If you pass the parameter **user** to postgres-database action and you use docker, that **user** is interpreted like a system user on the container.

`RuntimeError: ('postgres-database:\ndocker: Error response from daemon: unable to find user mossegada_user: no matching entries in passwd file.\n', [('postgres-database', 'docker: Error response from daemon: unable to find user mossegada_user: no matching entries in passwd file.\n')])`

**Comment by amgxv** [comment]
Changing the parameter name to pg_user worked for me : 
```
@action('postgres-database', output='stream:process')
def action_pgdump(_, params: dict): 
    pg_user = params.get('pg_user', 'postgres') <------
    pg_pass = params.get('password')
```

**Comment by melchor629** [comment]
Better if we remove the parameter `user` when calling to docker, like in mysql/maridb

```python
def action_psql_command(_, params: dict):
    docker = params.get('docker', False)
    run_as = params.get('runAs')
    if 'command' in params:
        del params['command']

    if docker:
        params['image'] = params.get('image', 'postgres:alpine')
        params['user'] = None <------
        return action_docker(None, params)
    ....
```

**Comment by amgxv** [comment]
That worked perfectly.
As you can see on top, I've created a pull request with the changes
