### ISSUE TITLE
Changing b2 library 

### ISSUE THREAD

**Issue by WardPearce** [MajorcaDevs/mdbackup#87]
Hey,
The `b2blaze` library hasn't been maintained for quite sometime, if you get a chance it would be awesome if you checked out my more new modern library for backblaze's b2.

https://github.com/WardPearce/backblaze
https://backblaze.readthedocs.io/en/latest/
https://pypi.org/project/backblaze/

Thanks,
Ward Pearce

**Comment by melchor629** [comment]
Hi WardPearce, thanks for letting us know about your package :) Will look at it because, as you said, `b2blaze` is not well maintained lately.
